
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

http:
  base_url: https://kota.koti:8123
  ssl_certificate: /etc/ssl/private/cert.pem
  ssl_key: /etc/ssl/private/key.pem

mqtt:
  broker: mosquitto
  port: 1883
  username: koti
  password: !env_var MQTT_PASSWORD

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

sensor:
  - friendly_name: Harmony Hub - Nykyinen Aktiviteetti
    name: harmony_hub_current_activity
    platform: mqtt
    state_topic: harmony-api/hubs/olohuone-v2/current_activity
  - friendly_name: Harmony Hub - Tila
    name: harmony_hub_state
    platform: mqtt
    state_topic: harmony-api/hubs/olohuone-v2/state
