apiVersion: 1

datasources:
  - name: "InfluxDB"
    orgId: 1
    id: 1
    type: "influxdb"
    access: "proxy"
    typeLogoUrl: "public/app/plugins/datasource/influxdb/img/influxdb_logo.svg"
    url: "http://influxdb:8086"
    password: ""
    user: ""
    database: "telegraf"
    basicAuth: false
    isDefault: true
    readOnly: false
