version: '3.7'
services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    restart: always
    entrypoint: /kota-entrypoint.sh
    ports:
      - "8883:8883"
      - "9091:9091"
    volumes:
      - ./mosquitto/kota-entrypoint.sh:/kota-entrypoint.sh:ro
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
      - ./certificates:/mosquitto/config/certs:ro
      - /etc/localtime:/etc/localtime:ro
    secrets:
      - MQTT_PASSWORD
    user: "1000:1000"

  zigbee2mqtt:
    image: koenkk/zigbee2mqtt
    container_name: zigbee2mqtt
    restart: always
    entrypoint: /kota-entrypoint.sh
    volumes:
      - ./zigbee2mqtt/kota-entrypoint.sh:/kota-entrypoint.sh:ro
      - ./zigbee2mqtt/data:/app/data
    secrets:
      - MQTT_PASSWORD
    environment:
      - TZ=Europe/Helsinki
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    depends_on:
      - mosquitto

  zigbee2mqttassistant:
    image: carldebilly/zigbee2mqttassistant
    container_name: zigbee2mqttassistant
    restart: always
    entrypoint: /kota-entrypoint.sh
    volumes:
      - ./zigbee2mqttassistant/kota-entrypoint.sh:/kota-entrypoint.sh:ro
    secrets:
      - MQTT_PASSWORD
    environment:
      - Z2MA_SETTINGS__MQTTSERVER=mosquitto
      - Z2MA_SETTINGS__MQTTUSERNAME=koti
      - TZ=Europe/Helsinki
    ports:
      - 8880:80
    depends_on:
      - mosquitto
    user: "1000:1000"

  node-red:
    image: nodered/node-red
    container_name: node-red
    restart: always
    entrypoint: /kota-entrypoint.sh
    volumes:
      - ./node-red/kota-entrypoint.sh:/kota-entrypoint.sh:ro
      - ./node-red/data:/data
      - ./certificates:/etc/ssl/private:ro
      - /etc/localtime:/etc/localtime:ro
    secrets:
      - MQTT_PASSWORD
    ports:
      - "1880:1880"
    depends_on:
      - mosquitto

  bt-mqtt-gateway:
    image: zewelor/bt-mqtt-gateway
    container_name: bt-mqtt-gateway
    restart: always
    entrypoint: /kota-entrypoint.sh
    volumes:
      - ./bt-mqtt-gateway/kota-entrypoint.sh:/kota-entrypoint.sh:ro
      - ./bt-mqtt-gateway/config.yaml.in:/config.yaml.in:ro
      - ./certificates:/certificates:ro
    secrets:
      - MQTT_PASSWORD
    # These capabilities are needed for Bluetooth
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_RESOURCE
    # The Docker host should have working Bluetooth
    network_mode: host
    depends_on:
      - mosquitto

  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    restart: always
    volumes:
      - ./influxdb/var:/var/lib/influxdb
    ports:
      - "8086:8086"
    user: "1000:1000"

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    volumes:
      - ./grafana/etc/provisioning:/etc/grafana/provisioning
      - ./grafana/lib:/var/lib/grafana
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    ports:
      - "3000:3000"
    depends_on:
      - influxdb
    user: "1000:1000"

  telegraf:
    image: telegraf
    container_name: telegraf
    restart: always
    entrypoint: /kota-entrypoint.sh
    secrets:
      - MQTT_PASSWORD
    volumes:
      - ./telegraf/kota-entrypoint.sh:/kota-entrypoint.sh:ro
      - ./telegraf/config:/etc/telegraf
    depends_on:
      - influxdb
      - mosquitto

  homeassistant:
    container_name: homeassistant
    image: homeassistant/home-assistant:stable
    restart: always
    entrypoint: /kota-entrypoint.sh
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Helsinki
    volumes:
      - ./homeassistant/config:/config
      - ./homeassistant/kota-entrypoint.sh:/kota-entrypoint.sh:ro
      - ./homeassistant/docker-venv/run:/etc/services.d/home-assistant/run
      - ./certificates:/etc/ssl/private:ro
      - /etc/localtime:/etc/localtime:ro
    secrets:
      - MQTT_PASSWORD
    depends_on:
      - mosquitto
    ports:
      - "8123:8123"

  heimdall:
    image: linuxserver/heimdall
    container_name: heimdall
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Helsinki
    volumes:
      - ./heimdall:/config
    ports:
      - "443:443"

secrets:
  MQTT_PASSWORD:
    file: ./secrets/MQTT_PASSWORD
