mqtt:
  host: localhost
  port: 8883
  username: koti
  password: MQTT_PASSWORD
  ca_cert: /certificates/cert.pem
  ca_verify: False
  topic_prefix: bt-mqtt-gateway
  client_id: bt-mqtt-gateway
  availability_topic: availability

manager:
  command_timeout: 30
  workers:
    ruuvitag:
      args:
        devices:
          sauna: FB:F4:05:4A:70:70
          makuuhuone: E2:7D:43:DE:99:0C
        topic_prefix: ruuvitag
      update_interval: 1
